from appWeb.views.aluno_view import *
from appWeb.views.curso_view import *
from appWeb.views.funcionario_view import *
from appWeb.views.ocorrencia_view import *
from appWeb.views.tipo_funcionario_view import *
from appWeb.views.tipo_oferta_view import *
from appWeb.views.tipo_ocorrencia_view import *
from appWeb.views.turma_view import *
from appWeb.views.appweb_view import *